// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package prototype

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// UserProfile contains the user personal information
type UserProfile struct {
	// Id is the user id which uniquely identify a user
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Email is the unique email of the user
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// FirstName is the user first name,it does not have any min length as it can
	// be empty too.
	FirstName string `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// LastName is the user last Name , it does not have any min length as it can
	// be empty too.
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserProfile) Reset()         { *m = UserProfile{} }
func (m *UserProfile) String() string { return proto.CompactTextString(m) }
func (*UserProfile) ProtoMessage()    {}
func (*UserProfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserProfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserProfile.Unmarshal(m, b)
}
func (m *UserProfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserProfile.Marshal(b, m, deterministic)
}
func (m *UserProfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserProfile.Merge(m, src)
}
func (m *UserProfile) XXX_Size() int {
	return xxx_messageInfo_UserProfile.Size(m)
}
func (m *UserProfile) XXX_DiscardUnknown() {
	xxx_messageInfo_UserProfile.DiscardUnknown(m)
}

var xxx_messageInfo_UserProfile proto.InternalMessageInfo

func (m *UserProfile) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UserProfile) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserProfile) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserProfile) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type CreateUserProfileRequest struct {
	UserProfile          *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateUserProfileRequest) Reset()         { *m = CreateUserProfileRequest{} }
func (m *CreateUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserProfileRequest) ProtoMessage()    {}
func (*CreateUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserProfileRequest.Unmarshal(m, b)
}
func (m *CreateUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserProfileRequest.Merge(m, src)
}
func (m *CreateUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserProfileRequest.Size(m)
}
func (m *CreateUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserProfileRequest proto.InternalMessageInfo

func (m *CreateUserProfileRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type GetUserProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserProfileRequest) Reset()         { *m = GetUserProfileRequest{} }
func (m *GetUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserProfileRequest) ProtoMessage()    {}
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *GetUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserProfileRequest.Unmarshal(m, b)
}
func (m *GetUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *GetUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserProfileRequest.Merge(m, src)
}
func (m *GetUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserProfileRequest.Size(m)
}
func (m *GetUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserProfileRequest proto.InternalMessageInfo

func (m *GetUserProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserProfileRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserProfileRequest) Reset()         { *m = DeleteUserProfileRequest{} }
func (m *DeleteUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserProfileRequest) ProtoMessage()    {}
func (*DeleteUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *DeleteUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserProfileRequest.Unmarshal(m, b)
}
func (m *DeleteUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserProfileRequest.Merge(m, src)
}
func (m *DeleteUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserProfileRequest.Size(m)
}
func (m *DeleteUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserProfileRequest proto.InternalMessageInfo

func (m *DeleteUserProfileRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type UpdateUserProfileRequest struct {
	UserProfile          *UserProfile `protobuf:"bytes,1,opt,name=user_profile,json=userProfile,proto3" json:"user_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpdateUserProfileRequest) Reset()         { *m = UpdateUserProfileRequest{} }
func (m *UpdateUserProfileRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserProfileRequest) ProtoMessage()    {}
func (*UpdateUserProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UpdateUserProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserProfileRequest.Unmarshal(m, b)
}
func (m *UpdateUserProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserProfileRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserProfileRequest.Merge(m, src)
}
func (m *UpdateUserProfileRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserProfileRequest.Size(m)
}
func (m *UpdateUserProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserProfileRequest proto.InternalMessageInfo

func (m *UpdateUserProfileRequest) GetUserProfile() *UserProfile {
	if m != nil {
		return m.UserProfile
	}
	return nil
}

type ListUsersProfilesRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersProfilesRequest) Reset()         { *m = ListUsersProfilesRequest{} }
func (m *ListUsersProfilesRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersProfilesRequest) ProtoMessage()    {}
func (*ListUsersProfilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ListUsersProfilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersProfilesRequest.Unmarshal(m, b)
}
func (m *ListUsersProfilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersProfilesRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersProfilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersProfilesRequest.Merge(m, src)
}
func (m *ListUsersProfilesRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersProfilesRequest.Size(m)
}
func (m *ListUsersProfilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersProfilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersProfilesRequest proto.InternalMessageInfo

func (m *ListUsersProfilesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type ListUsersProfilesResponse struct {
	Profiles             []*UserProfile `protobuf:"bytes,1,rep,name=profiles,proto3" json:"profiles,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListUsersProfilesResponse) Reset()         { *m = ListUsersProfilesResponse{} }
func (m *ListUsersProfilesResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersProfilesResponse) ProtoMessage()    {}
func (*ListUsersProfilesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *ListUsersProfilesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersProfilesResponse.Unmarshal(m, b)
}
func (m *ListUsersProfilesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersProfilesResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersProfilesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersProfilesResponse.Merge(m, src)
}
func (m *ListUsersProfilesResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersProfilesResponse.Size(m)
}
func (m *ListUsersProfilesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersProfilesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersProfilesResponse proto.InternalMessageInfo

func (m *ListUsersProfilesResponse) GetProfiles() []*UserProfile {
	if m != nil {
		return m.Profiles
	}
	return nil
}

func init() {
	proto.RegisterType((*UserProfile)(nil), "taskuser.UserProfile")
	proto.RegisterType((*CreateUserProfileRequest)(nil), "taskuser.CreateUserProfileRequest")
	proto.RegisterType((*GetUserProfileRequest)(nil), "taskuser.GetUserProfileRequest")
	proto.RegisterType((*DeleteUserProfileRequest)(nil), "taskuser.DeleteUserProfileRequest")
	proto.RegisterType((*UpdateUserProfileRequest)(nil), "taskuser.UpdateUserProfileRequest")
	proto.RegisterType((*ListUsersProfilesRequest)(nil), "taskuser.ListUsersProfilesRequest")
	proto.RegisterType((*ListUsersProfilesResponse)(nil), "taskuser.ListUsersProfilesResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4d, 0x4f, 0xfa, 0x40,
	0x10, 0xc6, 0x79, 0xf9, 0xf3, 0x0f, 0x9d, 0x12, 0x12, 0x36, 0x60, 0xd6, 0x12, 0x23, 0x59, 0x0f,
	0x1a, 0x0f, 0x45, 0xf1, 0xe2, 0xd9, 0x97, 0x98, 0x18, 0x43, 0x90, 0xc0, 0xc5, 0x83, 0xa4, 0x84,
	0x81, 0x34, 0xb6, 0xb4, 0xec, 0x6e, 0x0f, 0x7c, 0x2c, 0xbf, 0xa1, 0xe9, 0x96, 0x4a, 0xa5, 0x5d,
	0x4f, 0xde, 0x3a, 0xcf, 0x4c, 0x9f, 0x7d, 0x26, 0xbf, 0x01, 0x88, 0x04, 0x72, 0x3b, 0xe4, 0x81,
	0x0c, 0x48, 0x5d, 0x3a, 0xe2, 0x23, 0xae, 0xad, 0xee, 0x2a, 0x08, 0x56, 0x1e, 0xf6, 0x95, 0x3e,
	0x8f, 0x96, 0x7d, 0xf4, 0x43, 0xb9, 0x4d, 0xc6, 0x58, 0x00, 0xe6, 0x54, 0x20, 0x1f, 0xf1, 0x60,
	0xe9, 0x7a, 0x48, 0x9a, 0x50, 0x71, 0x17, 0xb4, 0xdc, 0x2b, 0x5f, 0x18, 0xe3, 0x8a, 0xbb, 0x20,
	0x6d, 0xa8, 0xa1, 0xef, 0xb8, 0x1e, 0xad, 0x28, 0x29, 0x29, 0xc8, 0x09, 0xc0, 0xd2, 0xe5, 0x42,
	0xce, 0xd6, 0x8e, 0x8f, 0xb4, 0xaa, 0x5a, 0x86, 0x52, 0x86, 0x8e, 0x8f, 0xa4, 0x0b, 0x86, 0xe7,
	0xa4, 0xdd, 0x7f, 0xaa, 0x5b, 0x8f, 0x85, 0xb8, 0xc9, 0x26, 0x40, 0xef, 0x39, 0x3a, 0x12, 0x33,
	0xcf, 0x8e, 0x71, 0x13, 0xa1, 0x90, 0xe4, 0x16, 0x1a, 0x71, 0xe2, 0x59, 0x98, 0xc8, 0x2a, 0x87,
	0x39, 0xe8, 0xd8, 0xe9, 0x2a, 0x76, 0xf6, 0x1f, 0x33, 0xda, 0x17, 0xec, 0x1c, 0x3a, 0x4f, 0x28,
	0x0b, 0x2c, 0x0f, 0x16, 0x62, 0x97, 0x40, 0x1f, 0xd0, 0xc3, 0xc2, 0xe7, 0x0f, 0x67, 0x27, 0x40,
	0xa7, 0xe1, 0xe2, 0xaf, 0xa3, 0x5e, 0x01, 0x7d, 0x71, 0x85, 0xca, 0x2a, 0x76, 0x9a, 0x48, 0x5d,
	0xdb, 0x50, 0xdb, 0x44, 0xc8, 0xb7, 0xbb, 0x10, 0x49, 0xc1, 0x86, 0x70, 0x5c, 0xf0, 0x87, 0x08,
	0x83, 0xb5, 0x40, 0x72, 0x0d, 0xf5, 0x5d, 0x06, 0x41, 0xcb, 0xbd, 0xaa, 0x3e, 0xc4, 0xf7, 0xd8,
	0xe0, 0xb3, 0x0a, 0x8d, 0x4c, 0x47, 0x90, 0x11, 0xb4, 0x72, 0x4c, 0x08, 0xdb, 0xdb, 0xe8, 0x80,
	0x59, 0xc5, 0x4f, 0xb1, 0x12, 0x79, 0x86, 0xe6, 0x4f, 0x1e, 0xe4, 0x74, 0x3f, 0x5a, 0x48, 0x4a,
	0xef, 0xf5, 0x0a, 0xad, 0x1c, 0xb2, 0x6c, 0x3a, 0x1d, 0x4f, 0xeb, 0xc8, 0x4e, 0x2e, 0xdf, 0x4e,
	0x2f, 0xdf, 0x7e, 0x8c, 0x2f, 0x9f, 0x95, 0xe2, 0x85, 0x73, 0x64, 0xb3, 0x96, 0x3a, 0xec, 0xfa,
	0x90, 0xef, 0xd0, 0xca, 0x31, 0xca, 0x3a, 0xea, 0x90, 0x5b, 0x67, 0xbf, 0xce, 0x24, 0x90, 0x59,
	0xe9, 0xce, 0x7c, 0x33, 0xd4, 0x16, 0x72, 0x1b, 0xe2, 0xfc, 0xbf, 0xfa, 0xbc, 0xf9, 0x0a, 0x00,
	0x00, 0xff, 0xff, 0xde, 0xbf, 0x72, 0xeb, 0xf0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserProfilesClient is the client API for UserProfiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserProfilesClient interface {
	// CreateProfile creates new user profile.
	CreateUserProfile(ctx context.Context, in *CreateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	// GetUserProfile returns the user profile by its unique user id.
	GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	// // DeleteUserProfile will delete the user profile from the system.
	DeleteUserProfile(ctx context.Context, in *DeleteUserProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error)
	ListUsersProfiles(ctx context.Context, in *ListUsersProfilesRequest, opts ...grpc.CallOption) (*ListUsersProfilesResponse, error)
}

type userProfilesClient struct {
	cc *grpc.ClientConn
}

func NewUserProfilesClient(cc *grpc.ClientConn) UserProfilesClient {
	return &userProfilesClient{cc}
}

func (c *userProfilesClient) CreateUserProfile(ctx context.Context, in *CreateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/taskuser.UserProfiles/CreateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/taskuser.UserProfiles/GetUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) DeleteUserProfile(ctx context.Context, in *DeleteUserProfileRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/taskuser.UserProfiles/DeleteUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) UpdateUserProfile(ctx context.Context, in *UpdateUserProfileRequest, opts ...grpc.CallOption) (*UserProfile, error) {
	out := new(UserProfile)
	err := c.cc.Invoke(ctx, "/taskuser.UserProfiles/UpdateUserProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userProfilesClient) ListUsersProfiles(ctx context.Context, in *ListUsersProfilesRequest, opts ...grpc.CallOption) (*ListUsersProfilesResponse, error) {
	out := new(ListUsersProfilesResponse)
	err := c.cc.Invoke(ctx, "/taskuser.UserProfiles/ListUsersProfiles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserProfilesServer is the server API for UserProfiles service.
type UserProfilesServer interface {
	// CreateProfile creates new user profile.
	CreateUserProfile(context.Context, *CreateUserProfileRequest) (*UserProfile, error)
	// GetUserProfile returns the user profile by its unique user id.
	GetUserProfile(context.Context, *GetUserProfileRequest) (*UserProfile, error)
	// // DeleteUserProfile will delete the user profile from the system.
	DeleteUserProfile(context.Context, *DeleteUserProfileRequest) (*empty.Empty, error)
	UpdateUserProfile(context.Context, *UpdateUserProfileRequest) (*UserProfile, error)
	ListUsersProfiles(context.Context, *ListUsersProfilesRequest) (*ListUsersProfilesResponse, error)
}

// UnimplementedUserProfilesServer can be embedded to have forward compatible implementations.
type UnimplementedUserProfilesServer struct {
}

func (*UnimplementedUserProfilesServer) CreateUserProfile(ctx context.Context, req *CreateUserProfileRequest) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUserProfile not implemented")
}
func (*UnimplementedUserProfilesServer) GetUserProfile(ctx context.Context, req *GetUserProfileRequest) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProfile not implemented")
}
func (*UnimplementedUserProfilesServer) DeleteUserProfile(ctx context.Context, req *DeleteUserProfileRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserProfile not implemented")
}
func (*UnimplementedUserProfilesServer) UpdateUserProfile(ctx context.Context, req *UpdateUserProfileRequest) (*UserProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUserProfile not implemented")
}
func (*UnimplementedUserProfilesServer) ListUsersProfiles(ctx context.Context, req *ListUsersProfilesRequest) (*ListUsersProfilesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUsersProfiles not implemented")
}

func RegisterUserProfilesServer(s *grpc.Server, srv UserProfilesServer) {
	s.RegisterService(&_UserProfiles_serviceDesc, srv)
}

func _UserProfiles_CreateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).CreateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskuser.UserProfiles/CreateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).CreateUserProfile(ctx, req.(*CreateUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_GetUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).GetUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskuser.UserProfiles/GetUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).GetUserProfile(ctx, req.(*GetUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_DeleteUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).DeleteUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskuser.UserProfiles/DeleteUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).DeleteUserProfile(ctx, req.(*DeleteUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_UpdateUserProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).UpdateUserProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskuser.UserProfiles/UpdateUserProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).UpdateUserProfile(ctx, req.(*UpdateUserProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserProfiles_ListUsersProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserProfilesServer).ListUsersProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/taskuser.UserProfiles/ListUsersProfiles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserProfilesServer).ListUsersProfiles(ctx, req.(*ListUsersProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserProfiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "taskuser.UserProfiles",
	HandlerType: (*UserProfilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUserProfile",
			Handler:    _UserProfiles_CreateUserProfile_Handler,
		},
		{
			MethodName: "GetUserProfile",
			Handler:    _UserProfiles_GetUserProfile_Handler,
		},
		{
			MethodName: "DeleteUserProfile",
			Handler:    _UserProfiles_DeleteUserProfile_Handler,
		},
		{
			MethodName: "UpdateUserProfile",
			Handler:    _UserProfiles_UpdateUserProfile_Handler,
		},
		{
			MethodName: "ListUsersProfiles",
			Handler:    _UserProfiles_ListUsersProfiles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
